CREATE TABLE "DP_Columns" (
"DP_ColumnID" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
"DP_TableID" INTEGER,
"Name" TEXT UNIQUE NOT NULL,
"DBName" TEXT UNIQUE NOT NULL,
"Datatype" TEXT NOT NULL,
"Metadata" TEXT
);


CREATE TABLE "DP_Tables" (
"DP_TableID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"Name" TEXT NOT NULL UNIQUE,
"DBName" TEXT NOT NULL UNIQUE
);